apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: motionlab-backend # Nama HelmRelease resource
  namespace: motionlab-backend     # Namespace tempat HelmRelease ini dibuat (dan tempat app di-deploy)
spec:
  interval: 5m # Seberapa sering FluxCD mencoba rekonsiliasi
  chart:
    spec:
      chart: ./motion-chart # Path relatif dari akar repo ke direktori chart dasar
      sourceRef:
        kind: GitRepository
        name: on-premise-infra # Nama GitRepository yang didefinisikan di apps/git-repository.yaml
        namespace: flux-system
      interval: 1m # Seberapa sering mengecek update chart dari source
  valuesFrom:
    - kind: ConfigMap
      name: motionlab-backend-values # Nama ConfigMap yang dibuat Kustomize
      # valuesKey: values.yaml # Opsional, defaultnya 'values.yaml' jika key di ConfigMap adalah 'values.yaml'