apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidm-api
  namespace: lidm
spec:
  interval: 1m
  install:
    timeout: 5m
  chart:
    spec:
      chart: "./motion-chart"
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m # Seberapa sering mengecek update chart dari source
  valuesFrom:
    - kind: ConfigMap
      name: lidm-values # Nama ConfigMap yang dibuat Kustomize
      valuesKey: values.yaml
      # valuesKey: values.yaml # Opsional, defaultnya 'values.yaml' jika key di ConfigMap adalah 'values.yaml'
