apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidm-api # Nama HelmRelease resource
  namespace: lidm     # Namespace tempat HelmRelease ini dibuat (dan tempat app di-deploy)
spec:
  interval: 5m # Seberapa sering FluxCD mencoba rekonsiliasi
  chart:
    spec:
      path: on-premise-infra-k8s-flux/motion-chart
      sourceRef:
        kind: GitRepository
        name: flux-system # Nama GitRepository yang didefinisikan di apps/git-repository.yaml
        namespace: flux-system
      interval: 1m # Seberapa sering mengecek update chart dari source
  valuesFrom:
    - kind: ConfigMap
      name: lidm-values # Nama ConfigMap yang dibuat Kustomize
      # valuesKey: values.yaml # Opsional, defaultnya 'values.yaml' jika key di ConfigMap adalah 'values.yaml'