apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-eventeens
spec:
  interval: 1m
  chart:
    spec:
      chart: "./motion-chart"
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: api-eventeens-values
      valuesKey: values.yaml
