# clusters/kubernetes-admin@kubernetes/apps/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace default untuk resource yang dibuat di sini jika tidak ditentukan secara eksplisit di resource itu sendiri
# namespace: default 

resources:
  - ./lidm/release.yaml
  # Tambahkan referensi ke HelmRelease instans lain di sini

configMapGenerator:
- name: lidm-values-configmap
  namespace: lidm
  files:
    - values.yaml=../../../motion-chart/lidm/values.yaml