# clusters/kubernetes-admin@kubernetes/apps/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace default untuk resource yang dibuat di sini jika tidak ditentukan secara eksplisit di resource itu sendiri
# namespace: default

resources:
  - git-repository.yaml
  - lidm/release.yaml

configMapGenerator:
  - name: lidm-values
    namespace: lidm
    files:
      - values.yaml=values/lidm-values.yaml
    options:
      disableNameSuffixHash: true
